### ISSUE TITLE
Wojak speech bubble hozzáadás

### ISSUE THREAD

**Issue by huntyh** [neonoxd/trashbot#11]
Legyen speech bubble wojakra esély mikor valaki valami hosszabb üzenetet ír (minél hosszabb, anál nagyobb esély?)

Pl.:
![image](https://user-images.githubusercontent.com/72654206/161050151-a44362ac-8557-415d-8fa4-a04e8b31423b.png)

**Comment by huntyh** [comment]
![wojak](https://user-images.githubusercontent.com/72654206/161055194-44e00dd9-d550-47ec-a3c2-83aab7a36b27.png)

itt van png-ként

**Comment by hmarcell** [comment]
hajrá @huntyh

**Comment by huntyh** [comment]
kész xd
