### ISSUE TITLE
Quote hozzáadás

### ISSUE THREAD

**Issue by huntyh** [neonoxd/trashbot#9]
Kéne egy fejlesztés ahhoz, hogy user tudjon paranccsal hozzáadni idézetet a meglévő poolba, aztán azt commanddal elő lehessen hívni (pl. most a k!zene és k!harap)

Először át kéne írni úgy, hogy command-group legyen az idézetre, szóval ne "k!zene" hanem "k!quote <alias>" legyen (ha sok híres személy van akkor igy jobban elkülöníthető sztem mintha csak sima command lenne)

Példa: k!quote harap

- [x] Task 1: "k!quote <alias>"  legyen a command a quotera

-----------------------------------------------------------------

Másodszor kéne egy command, amivel lehet hozzáadni híres személyt a poolba. Ez valahogy így nézhetne ki:
"k!quote create <alias> <hires_szemely_neve>"
A k!quote lenne az alap, a create mondja meg hogy új személyt akarunk a poolba felvenni, az <alias> változó pedig megmondja, mit kell beírni a commandba, hogy dobjon egy idézetet a bot.  (pl. "k!quote zene" esetén a "zene" az alias)

A <hires_szemely_neve> változót írjuk ki akkor, ha dob egy idézetet a bot, ez már most is így működik:

![image](https://user-images.githubusercontent.com/72654206/160455294-ea8e10ae-54ad-48fc-bee5-62ca100fd052.png)

Példa commandra: "k!quote create nyitas DJ Keleti Nyitás

- [x] Task 2: Lehessen "k!quote create <alias> <hires_szemely_neve>" vagy hasonló paranccsal hozzáadni új híres személyt, névvel meg aliassal

-----------------------------------------------------------------

Amúgy ezzel együtt lehetne egy "k!quote list" parancs is, ami listázza az idézhető forrásokat "<alias> - <hires_szemely_neve>" formátumban

- [x] Task 3: "k!quote list" parancs ami listázza a forrásokat "<alias> - <hires_szemely_neve>" vagy hasonló formátumban

-----------------------------------------------------------------

Ez után meg kéne egy command amivel konkrét idézeteket lehet hozzáadni. Formátuma lehetne "k!quote add <alias> <idezet>"
Példa: "k!quote add damu A gecibeeeeeeeeeee!"

- [x] Task 4: Legyen command idézet hozzáadásra "k!quote add <alias> <idezet>" vagy hasonló formátumban

-----------------------------------------------------------------

- [x] Bonus task: legyen "k!quote random" command teljesen random idézetre

Na csá. Zsidók vagytok mind.

**Comment by neonoxd** [comment]
no habla einglés

**Comment by hmarcell** [comment]
jo
